In [13]:
from google.colab import drive
import os

drive.mount("/content/drive")
os.chdir("/content/drive/My Drive/Colab Notebooks/thptqg-2025")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel(r"20250715-ketquathi-ct2018a.xlsx")
df.head()

,STT,SOBAODANH,Toán,Văn,Lí,Hóa,Sinh,Tin học,Công nghệ công nghiệp,Công nghệ nông nghiệp,Sử,Địa,Giáo dục kinh tế và pháp luật,Ngoại ngữ,Mã môn ngoại ngữ
0,1,1000001,5.75,7.75,NaN,7.75,8.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1000002,8.00,8.25,8.50,6.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1000003,6.75,8.50,8.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1000004,5.25,7.50,6.50,5.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1000005,NaN,7.00,NaN,NaN,NaN,NaN,NaN,NaN,5.5,6.25,NaN,NaN,NaN

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 15 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   STT                            1000000 non-null  int64
 1   SOBAODANH                      1000000 non-null  int64
 2   Toán                           995699 non-null   float64
 3   Văn                            996142 non-null   float64
 4   Lí                             309882 non-null   float64
 5   Hóa                            209552 non-null   float64
 6   Sinh                           56730 non-null    float64
 7   Tin học                        6057 non-null     float64
 8   Công nghệ công nghiệp          1939 non-null     float64
 9   Công nghệ nông nghiệp          18231 non-null    float64
 10  Sử                             421604 non-null   float64
 11  Địa                            421004 non-null   float64
 12  Giáo dục kinh tế và pháp luật  214574 non-null   float64
 13  Ngoại ngữ                      329878 non-null   float64
 14  Mã môn ngoại ngữ               329878 non-null   object
dtypes: float64(12), int64(2), object(1)
memory usage: 114.4+ MB

## Tiền xử lí bảng

In [16]:
score = df.columns.drop(labels = ["Mã môn ngoại ngữ", "SOBAODANH"])
df["Toán"] = df["Toán"].fillna(0)
df["Văn"] = df["Văn"].fillna(0)
df[score] = np.round(df[score].astype(np.float32), 2).astype(np.float16)

/usr/local/lib/python3.12/dist-packages/pandas/core/dtypes/astype.py:133: RuntimeWarning: overflow encountered in cast
  return arr.astype(dtype, copy=True)

In [17]:
df_new = df[["SOBAODANH", "Toán", "Văn", "Mã môn ngoại ngữ"]].copy()
df_new

/usr/local/lib/python3.12/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

        SOBAODANH  Toán   Văn Mã môn ngoại ngữ
0         1000001  5.75  7.75              NaN
1         1000002  8.00  8.25              NaN
2         1000003  6.75  8.50              NaN
3         1000004  5.25  7.50              NaN
4         1000005  0.00  7.00              NaN
...           ...   ...   ...              ...
999995   52013344  3.75  6.00              NaN
999996   52013345  4.25  7.25               N4
999997   52013346  3.75  7.75              NaN
999998   52013347  6.50  7.75              NaN
999999   52013348  3.25  6.75              NaN

[1000000 rows x 4 columns]

In [18]:
import pandas as pd
import numpy as np

# Danh sách môn phụ
mon_phu = df.columns.drop(["STT","SOBAODANH","Toán","Văn", "Mã môn ngoại ngữ"])


def processing_optional_subject(row):
    result = []
    for mon in mon_phu:
        if pd.notna(row[mon]):
            result.append({
                "SOBAODANH" : row["SOBAODANH"],
                "Môn phụ" : mon,
                "Điểm môn phụ" : row[mon]
            })

    return result

records = []
for idx, row in df.iterrows():
    records.extend(processing_optional_subject(row))

df_melt = pd.DataFrame(records)
df_melt["Điểm môn phụ"] = df_melt["Điểm môn phụ"].round(2)
df_melt

         SOBAODANH Môn phụ  Điểm môn phụ
0          1000001     Hóa          7.75
1          1000001    Sinh          8.25
2          1000002      Lí          8.50
3          1000002     Hóa          6.75
4          1000003      Lí          8.75
...            ...     ...           ...
1989446   52013346     Địa          8.50
1989447   52013347      Lí          6.50
1989448   52013347     Hóa          4.70
1989449   52013348      Lí          4.75
1989450   52013348     Hóa          3.35

[1989451 rows x 3 columns]

In [19]:
df_new = df_new.merge(df_melt, on="SOBAODANH", how="left")
df_new

/usr/local/lib/python3.12/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

         SOBAODANH  Toán   Văn Mã môn ngoại ngữ Môn phụ  Điểm môn phụ
0          1000001  5.75  7.75              NaN     Hóa          7.75
1          1000001  5.75  7.75              NaN    Sinh          8.25
2          1000002  8.00  8.25              NaN      Lí          8.50
3          1000002  8.00  8.25              NaN     Hóa          6.75
4          1000003  6.75  8.50              NaN      Lí          8.75
...            ...   ...   ...              ...     ...           ...
1989987   52013346  3.75  7.75              NaN     Địa          8.50
1989988   52013347  6.50  7.75              NaN      Lí          6.50
1989989   52013347  6.50  7.75              NaN     Hóa          4.70
1989990   52013348  3.25  6.75              NaN      Lí          4.75
1989991   52013348  3.25  6.75              NaN     Hóa          3.35

[1989992 rows x 6 columns]

In [20]:
df_new["Mã sở"] = (df_new["SOBAODANH"] // 1000000).astype(np.int8)
df_new["Số thứ tự tỉnh"] = (df_new["SOBAODANH"] % 1000000).astype(np.int32)
df_new.drop(columns = ["SOBAODANH"], inplace = True)

In [21]:
max(df_new["Mã sở"])

52

In [23]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1989992 entries, 0 to 1989991
Data columns (total 7 columns):
 #   Column            Dtype
---  ------            -----
 0   Toán              float16
 1   Văn               float16
 2   Mã môn ngoại ngữ  object
 3   Môn phụ           object
 4   Điểm môn phụ      float64
 5   Mã sở             int8
 6   Số thứ tự tỉnh    int32
dtypes: float16(2), float64(1), int32(1), int8(1), object(2)
memory usage: 62.6+ MB

In [22]:
df_new.to_csv("bang_diem_sau_tien_xu_li.csv")